spring.application.name=smart-erp-application

server.port=9521

spring.datasource.url=${SUPABASE-URL}
spring.datasource.username=${SUPABASE-USERNAME}
spring.datasource.password=${SUPABASE-PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

// SQL Initialization
spring.sql.init.mode=always

jwt.secret=${JWT-SECRET}
jwt.expiration=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.jackson.time-zone=Asia/Kolkata