import React from 'react';
import { useActiveCompany } from '@shared/context/ActiveCompanyContext';
import { useAuth } from '@shared/context/AuthContext';
import { Building2 } from 'lucide-react';

export default function PrintHeader({ title = "Report", filtersApplied = "" }) {
  const { activeCompany } = useActiveCompany();
  const { user } = useAuth();
  
  const generatedTime = new Date().toLocaleString('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short'
  });

  return (
    <div className="print-only-header w-full border border-neutral-300 rounded-xl p-6 mb-6 bg-white text-neutral-800 font-sans">
      <div className="flex justify-between items-start border-b border-neutral-200 pb-4 mb-4">
        {/* Left side: Company Details */}
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-indigo-50 border border-indigo-100 flex items-center justify-center text-indigo-600">
            <Building2 size={20} />
          </div>
          <div>
            <h1 className="text-base font-bold tracking-tight text-neutral-900 leading-tight">
              {activeCompany?.name || 'SmartERP Enterprise'}
            </h1>
            <p className="text-[10px] text-neutral-500 font-mono mt-0.5 leading-none">
              GSTIN: {activeCompany?.gstNumber || 'N/A'} | Financial Year: {activeCompany?.financialYear || 'N/A'}
            </p>
          </div>
        </div>

        {/* Right side: Report metadata */}
        <div className="text-right">
          <h2 className="text-sm font-bold text-neutral-900 leading-tight uppercase tracking-wider">
            {title}
          </h2>
          <p className="text-[9px] text-neutral-500 font-mono mt-1 leading-none">
            Gen: {generatedTime}
          </p>
        </div>
      </div>

      {/* Row details for execution parameters */}
      <div className="grid grid-cols-3 gap-4 text-[10px] text-neutral-600">
        <div>
          <span className="font-semibold text-neutral-800">Generated By:</span>
          <span className="ml-1 font-mono">{user?.fullName || 'System User'}</span>
        </div>
        <div className="col-span-2 text-right">
          <span className="font-semibold text-neutral-800">Filters Applied:</span>
          <span className="ml-1 italic text-neutral-500 font-sans">
            {filtersApplied || 'None (Full Dataset)'}
          </span>
        </div>
      </div>
    </div>
  );
}
